### ISSUE TITLE
Get the uuid of the quiz before it's over

### ISSUE THREAD

**Issue by IcyCoder368** [theusaf/kahoot.js-updated#43] opened 2020-07-01 22:20 UTC
I think it would be cool to be able to get the uuid of the quiz before it's over. This could be useful for using `kahoot-search` to find the quiz and the questions / answers. It would also be a very handy feature to be able to know the author of the quiz, also for use with `kahoot-search`.

**Comment by theusaf** [comment] 2020-07-02 14:55
Closing because this is a duplicate of #28

**Closed by theusaf** 2020-07-02 14:55 UTC
Labels: duplicate, enhancement, wontfix
