### ISSUE TITLE
Script crashing after answer streak - TypeError: Cannot read property 'answerStreakPoints' of undefined

### ISSUE THREAD

**Issue by GunnerBasil** [theusaf/kahoot.js-updated#78] opened 2021-01-22 17:38 UTC
**Describe the bug**
Script crashing after bot (kahoot.js-updated player) gets an answer streak
`TypeError: Cannot read property 'answerStreakPoints' of undefined`
![image](https://user-images.githubusercontent.com/57513430/105524651-28428100-5c9d-11eb-94f3-5d2295c54c2e.png)

**To Reproduce**
1. Get a player to answer a correct answer twice.
2. Should crash.

**Expected behavior**
Nothing to happen, for the script to continue running as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/57513430/105524731-460fe600-5c9d-11eb-9206-bc193767c10e.png)

**System (please complete the following information):**
 - OS: Windows 10

**Additional context**
This might not be applicable to anyone else since I'm using a discord.js bot to run the commands.

**Comment by theusaf** [comment] 2021-01-22 18:28
Are you using the latest version? (Check your `package.json` and make sure it is `2.3.2`

Line 79 (where the error occurred in the screenshot) is the following:
` * @property {Number} questionCount The number of questions.`

I think I had run into this issue a while ago, which should have been fixed in `2.3.1`

**Comment by theusaf** [comment] 2021-02-06 17:40
Closing due to inactivity, unable to reproduce.

**Closed by theusaf** 2021-02-06 17:40 UTC
Labels: bug, unconfirmed
